version: "3.9"
services:
  mullvad-wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: mullvad-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/mullvad-tailscale/wireguard:/config:Z
      - /lib/modules:/lib/modules:ro
    ports:
      - 52000:51820/udp
      # Firefox Browser
      - 5800:5800
      - 5900:5900
      # Tor Browser
      - 6800:6800
      - 6900:6900
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    healthcheck:
      test: curl --fail 1.1.1.1 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  mullvad-tailscale:
    privileged: true
    container_name: mullvad-tailscale
    image: tailscale/tailscale:latest
    volumes:
      - /services/mullvad-tailscale/tailscale:/var/lib/tailscale
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    command: tailscaled
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - mullvad-wireguard
    network_mode: service:mullvad-wireguard
    healthcheck:
      test: wget -qO- tailscale.com &> /dev/null || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  mullvad-firefox:
    image: jlesage/firefox
    container_name: mullvad-firefox
    restart: unless-stopped
    volumes:
      - /services/mullvad-tailscale/firefox:/config
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      KEEP_APP_RUNNING: 1
      TZ: America/New_York
    depends_on:
      - mullvad-wireguard
    network_mode: service:mullvad-wireguard
    shm_size: 2g
    healthcheck:
      test: wget -qO- localhost:5800 &> /dev/null || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  mullvad-tor:
    image: domistyle/tor-browser
    container_name: mullvad-tor
    restart: unless-stopped
    volumes:
      - /services/mullvad-tailscale/tor:/config
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      KEEP_APP_RUNNING: 1
      TZ: America/New_York
      WEB_LISTENING_PORT: 6800
      VNC_LISTENING_PORT: 6900
    depends_on:
      - mullvad-wireguard
    network_mode: service:mullvad-wireguard
    shm_size: 2g
    healthcheck:
      test: wget -qO- localhost:6800 &> /dev/null || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s