version: "3.9"
services:
  wireguard-mullvad-usa:
    image: ghcr.io/linuxserver/wireguard
    container_name: mullvad-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/mullvad-usa/wireguard:/config:Z
      - /lib/modules:/lib/modules:ro
    ports:
      - 53000:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    healthcheck:
      test: curl --fail https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  tailscale-mullvad-usa:
    container_name: tailscale-mullvad-usa
    image: tailscale/tailscale:latest
    volumes:
      - /services/mullvad-usa/tailscale:/var/lib/tailscale
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    command: tailscaled --tun=userspace-networking
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - wireguard-mullvad-usa
    network_mode: service:wireguard-mullvad-usa
    healthcheck:
      test: wget -qO- --no-verbose --tries=1 https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s