version: '3.9'
services:
  poste-io:
    image: docker.io/analogic/poste.io
    volumes:
      - /services/poste/data:/data
    ports:
      - "2025:25"
      - 2110:110 
      - 2143:143 
      - 2465:465 
      - 2587:587 
      - 2993:993 
      - 2995:995
    restart: unless-stopped
    networks:
      - poste
    environment:
      - TZ=America/New_York
      - HTTPS=OFF

networks:
  poste:
    name: poste
    external: true