version: "3.9"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=jellyfin.bspwr.com #optional
    volumes:
      - /services/jellyfin/config:/config:Z
      - /ocean/media/shows:/data/shows:z
      - /ocean/media/movies:/data/movies:z
      - /ocean/media/music:/data/music:z
      - /ocean/media/books:/data/books:z       
      - /ocean/media/pictures:/data/pictures:z
      - /ocean/media/xxx:/data/xxx:z
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:8096 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s