version: "3.9"
services:
  nginx-proxy-manager:
    build: .
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - target: 80 # Public HTTP Port
        published: 1080 # Outside port
        mode: host
        protocol: tcp
      - target: 443 # Public HTTPS Port
        published: 1443 # Outside port
        mode: host
        protocol: tcp
      - target: 81 # Admin Web Port
        published: 1081 # Outside port
        mode: host
        protocol: tcp
      - target: 4242 # Mullvad USA SOCKS Proxy
        published: 4242 # Outside port
        mode: host
        protocol: tcp
      - target: 6969 # Mullvad Sweden SOCKS Proxy
        published: 6969 # Outside port
        mode: host
        protocol: tcp
      - target: 4444 # I2P HTTP Proxy
        published: 4444 # Outside port
        mode: host
        protocol: tcp
      - target: 9050 # Tor SOCKS Proxy
        published: 9050 # Outside port
        mode: host
        protocol: tcp
      - target: 18089 # Monero Node
        published: 18089 # Outside port
        mode: host
        protocol: tcp
    volumes:
      - /services/nginx-proxy-manager/data:/data
      - /services/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: curl --fail localhost:81 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 1s