version: '3.9'
services:
  lxdware-dashboard:
    build: ./docker
    container_name: lxdware-dashboard
    volumes:
      - /services/lxdware/lxdware:/var/lxdware
    networks:
      - lxdware
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:80 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

networks:
  lxdware:
    name: lxdware
    external: true