version: "3.9"
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    hostname: filebrowser
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /ocean/services/filebrowser:/srv
      - /services/filebrowser/database:/database
      - /services/filebrowser/config:/config
    ports:
      - 6080:80
    restart: unless-stopped

  filebrowser-downloads:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser-downloads
    hostname: filebrowser-downloads
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /ocean/downloads:/srv:ro
      - /services/filebrowser/database-downloads:/database
      - /services/filebrowser/config-downloads:/config
    ports:
      - 6090:80
    restart: unless-stopped