version: "3.9"
services:
  wireguard-mullvad-sweden:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard-mullvad-sweden
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1420
      - PGID=1420
      - TZ=America/New_York
    volumes:
      - /services/mullvad-sweden/wireguard:/config:Z
      - /lib/modules:/lib/modules:ro
    ports:
      - 52000:51820/udp
      # Firefox Browser
      - 6600:6600
      - 6700:6700
      # Tor Browser
      - 6800:6800
      - 6900:6900
      # SOCKS Proxy
      - 6960:6960
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    healthcheck:
      test: curl --fail https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s

  tailscale-mullvad-sweden:
    container_name: tailscale-mullvad-sweden
    image: tailscale/tailscale:latest
    volumes:
      - /services/mullvad-sweden/tailscale:/var/lib/tailscale
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    command: tailscaled --tun=userspace-networking
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - wireguard-mullvad-sweden
    network_mode: service:wireguard-mullvad-sweden
    healthcheck:
      test: wget -qO- --no-verbose --tries=1 https://am.i.mullvad.net/connected | grep "You are connected to Mullvad" || exit 1
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 2s

  firefox-mullvad-sweden:
    image: jlesage/firefox
    container_name: firefox-mullvad-sweden
    restart: unless-stopped
    volumes:
      - /services/mullvad-sweden/firefox:/config
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      KEEP_APP_RUNNING: 1
      TZ: America/New_York
      WEB_LISTENING_PORT: 6600
      VNC_LISTENING_PORT: 6700
    depends_on:
      - wireguard-mullvad-sweden
    network_mode: service:wireguard-mullvad-sweden
    shm_size: 2g
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:6600 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  tor-mullvad-sweden:
    build: ./tor-docker
    container_name: tor-mullvad-sweden
    restart: unless-stopped
    volumes:
      - /services/mullvad-sweden/tor:/config
    environment:
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      KEEP_APP_RUNNING: 1
      TZ: America/New_York
      WEB_LISTENING_PORT: 6800
      VNC_LISTENING_PORT: 6900
    depends_on:
      - wireguard-mullvad-sweden
    network_mode: service:wireguard-mullvad-sweden
    shm_size: 2g
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:6800 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 2s

  socks-proxy-mullvad-sweden:
    container_name: socks-proxy-mullvad-sweden
    image: serjs/go-socks5-proxy
    environment:
      - PROXY_PORT=6960
    restart: unless-stopped
    depends_on:
      - wireguard-mullvad-sweden
    network_mode: service:wireguard-mullvad-sweden