version: '3.9'
services:
  headscale:
    image: headscale/headscale:latest-alpine
    container_name: headscale
    volumes:
      - /services/headscale/config:/etc/headscale
      - /services/headscale/data:/var/lib/headscale
    networks:
      - headscale
    command: headscale serve
    restart: unless-stopped

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    networks:
      - headscale

networks:
  headscale:
    name: headscale
    external: true