version: '3.9'
services:
  minecraft-atm8-rcon:
    image: docker.io/itzg/rcon
    container_name: minecraft-atm8-rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: 1337taco
      RWA_ADMIN: "true"
      # is referring to the hostname of minecraft container
      RWA_RCON_HOST: minecraft-atm8
      # needs to match the password configured for the container, which is 'minecraft' by default
      RWA_RCON_PASSWORD: minecraft
      RWA_WEBSOCKET_URL_SSL: "wss://minecraft-rcon.bspwr.com/websocket"
      RWA_WEBSOCKET_URL: "ws://minecraft-rcon.bspwr.com/websocket"
    ports:
      - 4326:4326 # web UI
      - 4327:4327 # websocket access from UI
    depends_on:
      - minecraft-atm8
    healthcheck:
      test: curl --fail localhost:4326 || exit 1
      interval: 10s
      retries: 6
      start_period: 10s
      timeout: 1s

  minecraft-atm8:
    image: docker.io/itzg/minecraft-server
    container_name: minecraft-atm8
    hostname: minecraft-atm8
    ports:
      - 25565:25565
    volumes:
      - /services/minecraft-atm8/data:/data
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      TYPE: "FORGE"
      FORGEVERSION: "43.1.55"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "12G"
