version: '3.9'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /services/portainer/data:/data
    ports:
      - 9443:9443
    restart: unless-stopped