version: '3.9'
services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /services/portainer/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9443:9443
    restart: unless-stopped
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider --no-check-certificate https://localhost:9443 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s